name: rm file

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: before DISKSPACE
      run: |
        echo "before DISKSPACE"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        
    - name: organ rm apt  
    
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc


    - name: middle DISKSPACE
      run: |
        echo "middle DISKSPACE"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: "Optimize Disk Space"
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: |-
          ^GCC$
          ^G\+\+$
          Clang
          LLVM
        docker_include: ".+"
        docker_prune: "True"
        docker_clean: "True"
        apt_prune: "True"
        apt_clean: "True"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: Third DISKSPACE
      run: |
        echo "Third DISKSPACE"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Freeing up disk space
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 2048
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'


    - name: Final FREE DISKSPACE complete
      run: |
        echo "Final FREE DISKSPACE complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

      
