  name: seediskspace

  env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

  jobs:
  build:
    runs-on: ubuntu-20.04
  steps:
  - name: Final FREE DISKSPACE complete
      run: |
        echo "Final FREE DISKSPACE complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
